# A workflow for gitlab ci
variables:
  APT_PKGS: "libcurl4-openssl-dev libssl-dev libxt6"
  #RENV_CONFIG_REPOS_OVERRIDE: "http://cran.r-project.org"
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library

cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}


  
  before_script:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"
  
  script:
    - mkdir private  
    - Rscript -e "rmarkdown::render('Consecrated life today/Consecrated_life_today.Rmd')"
  artifacts:
    paths:
      - private
    when: always

# setup steps
run:
  tags:
      - docker
  image: rocker/verse:4.0.5
