article:
  stage: deploy
  image: rocker/verse:4.0.5
  variables:
  RENV_CONFIG_REPOS_OVERRIDE: "http://cran.r-project.org"
  before_script:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"
  script:
    - Rscript -e "remove.packages('rticles')" -e "devtools::install_github('nuest/rticles', ref = 'copernicus')"
    - Rscript -e "rmarkdown::render('MyArticle/MyArticle.Rmd')"
  artifacts:
    paths:
      - MyArticle
    when: always
